#Data Source Properties
spring:
  datasource:
#    url: "jdbc:mysql://root:3871@localhost:3306/aviobrief_sql?serverTimezone=UTC&characterEncoding=UTF-8&sslMode=DISABLED&createDatabaseIfNotExist=true"
    url: "jdbc:mysql://bca7d6a943a13c:b6d2221d@us-cdbr-east-05.cleardb.net/heroku_4ef45b91ee2c27a?reconnect=true&serverTimezone=UTC&characterEncoding=UTF-8&createDatabaseIfNotExist=true"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    connection-test-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      continue-on-error: true

#Server config
server:
  port: 8000
  error:
    include-message: always

## App Properties
app:
  jwt-secret: "mySuperSecret"
  jwt-expiration-mills: 604800000
  completable-await-time-seconds: 30


